### ISSUE TITLE
CSV file with user details exposed 

### ISSUE THREAD

**Issue by hazelwolf** [openiitbombayx/blendedmoocs-mis#1]
Hi Team 

Your csv files are public and exposes user information that might get you in trouble.  I am one of the students attending MOOC and this thing just came over google when I searched my name. You guys might want to look into it.

https://github.com/openiitbombayx/blendedmoocs-mis/blob/9a94d53106048e6fe6618a3c8f3f914641b656e1/IITBOMBAYX_PARTNERS/static/closed_courses/IITBombayX_ME209xA15_2015_T1_grade_details.csv

**Comment by openiitbombayx** [comment]
Thanks for the information. We removed the csv's.
